[platformio]
default_envs = native_test_runner, integration_test, native_test

[env:native_test_runner]
platform = native
test_framework = unity
test_build_src = yes
build_flags = 
    -Iinclude
    -Isrc
    -DPLATFORM_LINUX
    -D_GNU_SOURCE
    -D_DEFAULT_SOURCE
    -g3
    -Wall -Wextra -std=c99
build_src_filter = 
    +<core/*>
    +<profiles/*>
    +<protocols/*>
    +<hal/hal_native/*>
test_filter = test_protocol_parser

[env:integration_test]
platform = native
test_framework = unity
test_build_src = yes
build_flags = 
    -Iinclude
    -Isrc
    -DPLATFORM_LINUX
    -D_GNU_SOURCE
    -D_DEFAULT_SOURCE
    -g3
    -Wall -Wextra -std=c99
build_src_filter = 
    +<core/*>
    +<profiles/*>
    +<protocols/*>
    +<hal/hal_native/*>
test_filter = test_integration

[env:native_test]
platform = native
test_ignore = *
build_flags = 
    -Iinclude
    -Isrc
    -DPLATFORM_LINUX
    -D_GNU_SOURCE
    -D_DEFAULT_SOURCE
    -Wall -Wextra -std=c99
build_src_filter = 
    +<main.c>
    +<core/*>
    +<profiles/*>
    +<protocols/*>
    +<hal/hal_native/*>

