[platformio]
default_envs = native_test_runner, integration_test, native_test

[env:native_test_runner]
platform = native
test_framework = unity
test_build_src = yes
build_flags = 
    -Iinclude
    -Isrc
    -DPLATFORM_LINUX
    -D_GNU_SOURCE
    -D_DEFAULT_SOURCE
    -g3
    -Wall -Wextra -std=c99
build_src_filter = 
    +<core/*>
    +<profiles/*>
    +<protocols/*>
    +<hal/hal_native/*>
test_filter = test_protocol_parser

[env:integration_test]
platform = native
test_framework = unity
test_build_src = yes
build_flags = 
    -Iinclude
    -Isrc
    -DPLATFORM_LINUX
    -D_GNU_SOURCE
    -D_DEFAULT_SOURCE
    -g3
    -Wall -Wextra -std=c99
build_src_filter = 
    +<core/*>
    +<profiles/*>
    +<protocols/*>
    +<hal/hal_native/*>
test_filter = test_integration

[env:native_test]
platform = native
test_ignore = *
build_flags = 
    -Iinclude
    -Isrc
    -DPLATFORM_LINUX
    -D_GNU_SOURCE
    -D_DEFAULT_SOURCE
    -Wall -Wextra -std=c99
build_src_filter = 
    +<main.c>
    +<core/*>
    +<profiles/*>
    +<protocols/*>
    +<hal/hal_native/*>

[env:stm32_cbox]
platform = ststm32
board = bluepill_f103c8
framework = stm32cube
test_ignore = *
build_flags = 
    -Iinclude
    -Isrc
    -DPLATFORM_STM32
    -DUSE_FULL_LL_DRIVER
    -Wall -Wextra -std=c99
build_src_filter = 
    +<main.c>
    +<core/*>
    +<protocols/*>
    +<hal/hal_stm32/*>

[env:esp32_cbox]
platform = espressif32
board = esp32dev
framework = espidf
monitor_speed = 115200
test_ignore = *
build_flags = 
    -Iinclude
    -Isrc
    -DPLATFORM_ESP32
    -Wall -Wextra -std=c99
build_src_filter = 
    +<core/*>
    +<protocols/*>
    +<hal/hal_esp32/*>
    +<main_esp32.c>
