[platformio]
default_envs = native_test

[env:integration_test]
platform = native
test_framework = unity
build_flags = 
    -Iinclude
    -Isrc
    -DPLATFORM_LINUX
    -Wall -Wextra -std=c99
build_src_filter = 
    +<core/*>
    +<profiles/*>
    +<protocols/*>
test_filter = test_integration

[env:native_test]
platform = native
build_flags = 
    -Iinclude
    -Isrc
    -DPLATFORM_LINUX
    -D_GNU_SOURCE
    -D_DEFAULT_SOURCE
    -Wall -Wextra -std=c99
build_src_filter = 
    +<main.c>
    +<core/*>
    +<profiles/*>
    +<protocols/*>
    +<hal/hal_native/*>
